# Basic config
baseURL = "https://leespeak.me"
theme = "hugo-simple"
languageCode = "en"                # zh-Hans
title = "LEE_SPEAK"
# copyright = "© 2024 Shaolong Chen"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# https://github.com/gohugoio/hugo/issues/12152
capitalizeListTitles = false

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
# ignoreErrors = ["error-disable-taxonomy"]
[taxonomies]
tag = "tags"

[permalinks]
blog = "/:slugorcontentbasename/"
tags = "/blog/:slug"

[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 2
endLevel = 3
[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "catppuccin-mocha"

[params]
title = "Hugo Simple"
description = "Hugo Simple Demo"
favicon = "images/favicon.png"
dateFormat = "2006-01-02"
hideMadeWithLine = true
hideRSSLink = true

[params.author]
name = "Liam McKenna"
email = "lee@liamdouglas.com"

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10
[[menu.main]]
name = "Gaming"
pageRef = "/gaming"
weight = 20
[[menu.main]]
name = "Music"
pageRef = "/music"
weight = 30
[[menu.main]]
name = "Misc."
pageRef = "/miscellaneous"
weight = 40
[[menu.main]]
name = "PokéLeef"
pageRef = "/pokeleef/"
weight = 50
[[menu.main]]
name = "Sweet Synopsis"
pageRef = "/sweet_synopsis"
weight = 60

[services.rss]
limit = 42

[pagination]
pagerSize = 16

[outputs]
# Generate RSS for home only.
section = ["html"]
taxonomy = ["html"]
term = ["html"]
